language: php

php:
  - 5.5

env:
  matrix:
    - TYPO3_VERSION=7.6.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  - composer require codeclimate/php-test-reporter
  - mkdir -p ../../default.instance/typo3conf/ext/
  - ln -s ../../../heiko-hardt/t3ee_voting_example ../../default.instance/typo3conf/ext/t3ee_voting_example
  - cd ../../default.instance
  - export TYPO3_PATH_WEB=/home/travis/build/default.instance

script:
  - echo
  - echo "Processing php unit tests"
  - >
    ./bin/phpunit
    --coverage-clover=/home/travis/build/heiko-hardt/t3ee_voting_example/build/logs/clover.xml
    --configuration typo3conf/ext/t3ee_voting_example/Build/UnitTests.travis.xml
    typo3conf/ext/t3ee_voting_example/Tests/Unit;

  - echo
  - echo "Commit code coverage to scrutinizer"
  - >
    cd /home/travis/build/heiko-hardt/t3ee_voting_example;
    wget https://scrutinizer-ci.com/ocular.phar;
    php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml;

  - echo
  - echo "Commit code coverage to codeclimate"
  - >
    cd /home/travis/build/heiko-hardt/t3ee_voting_example;
    CODECLIMATE_REPO_TOKEN=47b2af3d4e98207ec94893d047cb4c9415902a03b9a7c487c9e654ff42613738
    /home/travis/build/default.instance/bin/test-reporter;
